version: "3.9"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MONGO_INITDB_APP_USERNAME: ${APP_USERNAME}
      MONGO_INITDB_APP_PASSWORD: ${APP_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/tmp/geo
      - ./mongo/initDB.sh:/docker-entrypoint-initdb.d/1-init.sh
      - ./mongo/initUser.js:/docker-entrypoint-initdb.d/2-init.js

  geo_api:
    depends_on:
      - mongo
    build: .
    container_name: geo_api
    restart: unless-stopped
    environment:
      MONGO_DB_HOSTNAME: mongo
      MONGO_DB_USERNAME: ${APP_USERNAME}
      MONGO_DB_PASSWORD: ${APP_PASSWORD}
    ports:
      - "8080:8080"

#  mongo-express:
#    container_name: mongo-express
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ROOT_USERNAME}
#      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ROOT_PASSWORD}
#      ME_CONFIG_MONGODB_PORT: 27017
#      ME_CONFIG_MONGODB_SERVER: mongo
